# Generated by Django 5.2.6 on 2025-09-25 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_reminderconfiguration_contribution_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('PAYMENT_REMINDER', 'Rappel de paiement'), ('PAYMENT_CONFIRMATION', 'Confirmation de paiement'), ('OVERDUE_NOTICE', 'Avis de retard'), ('LEGAL_NOTICE', 'Avis légal'), ('GENERAL_ANNOUNCEMENT', 'Annonce générale')], max_length=30)),
                ('subject', models.CharField(help_text='Sujet pour email', max_length=200)),
                ('email_template', models.TextField(help_text='Template email (HTML supporté)')),
                ('sms_template', models.TextField(help_text='Template SMS (max 160 caractères)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SMSService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('TWILIO', 'Twilio'), ('SMS_MAROC', 'SMS Maroc'), ('INWI', 'Inwi'), ('IAM', 'IAM'), ('CUSTOM', 'Service personnalisé')], max_length=50)),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(max_length=200)),
                ('api_secret', models.CharField(blank=True, max_length=200)),
                ('sender_id', models.CharField(help_text="Nom ou numéro d'expéditeur", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('BOTH', 'Email + SMS')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'En attente'), ('DELIVERED', 'Livré'), ('FAILED', 'Échec'), ('BOUNCED', 'Rejeté')], default='PENDING', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='ID externe du service de notification', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.notificationtemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, help_text='Numéro de téléphone pour SMS', max_length=20)),
                ('reminder_frequency', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('NEVER', 'Jamais')], default='WEEKLY', max_length=20)),
                ('advance_notice_days', models.PositiveIntegerField(default=5, help_text="Jours d'avance pour les rappels")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
