# Generated by Django 5.2.6 on 2025-09-26 06:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_notificationtemplate_smsservice_notificationlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PAYMENT_REMINDER', 'Rappel de paiement'), ('PAYMENT_CONFIRMATION', 'Confirmation de paiement'), ('OVERDUE_NOTICE', 'Avis de retard'), ('LEGAL_NOTICE', 'Avis légal'), ('GENERAL_ANNOUNCEMENT', 'Annonce générale'), ('MEETING_NOTICE', 'Convocation réunion')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipients', models.ManyToManyField(related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='template',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymenttracking',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReminderConfiguration',
        ),
        migrations.RemoveField(
            model_name='reminderlog',
            name='contribution',
        ),
        migrations.DeleteModel(
            name='SMSService',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreferences',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='note',
        ),
        migrations.AddField(
            model_name='contribution',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('CLEANING', 'Nettoyage'), ('SECURITY', 'Sécurité'), ('UTILITIES', 'Services publics'), ('REPAIRS', 'Réparations'), ('OTHER', 'Autres')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Dépense', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.contribution'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('BANK_TRANSFER', 'Virement bancaire'), ('CHECK', 'Chèque'), ('CARD', 'Carte bancaire'), ('OTHER', 'Autre')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='period',
            field=models.CharField(help_text='Ex: 2024-01', max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('LATE', 'En retard'), ('OVERDUE_30', 'Retard 30+ jours'), ('OVERDUE_60', 'Retard 60+ jours'), ('OVERDUE_90', 'Retard 90+ jours')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
        migrations.DeleteModel(
            name='PaymentTracking',
        ),
        migrations.DeleteModel(
            name='ReminderLog',
        ),
        migrations.DeleteModel(
            name='UserNotificationPreferences',
        ),
    ]
