# Generated by Django 5.2.6 on 2025-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_notification_remove_notificationlog_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text="Justificatif de paiement (reçu, capture d'écran, etc.)", null=True, upload_to='payment_proofs/%Y/%m/'),
        ),
    ]
