# Generated by Django 5.2.6 on 2025-09-26 07:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_payment_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT_REMINDER', 'Rappel de paiement'), ('DOCUMENT_UPLOADED', 'Nouveau document'), ('GENERAL_ANNOUNCEMENT', 'Annonce générale'), ('MEETING_NOTICE', 'Convocation réunion'), ('LEGAL_NOTICE', 'Avis légal'), ('OTHER', 'Autre')], default='GENERAL_ANNOUNCEMENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(limit_choices_to={'role': 'RESIDENT'}, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'role__in': ['SUPERADMIN', 'SYNDIC']}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPERADMIN', 'SYNDIC']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du document', max_length=200)),
                ('file', models.FileField(help_text='Fichier du document', upload_to='documents/%Y/%m/')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant en DH', max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date du document')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Facture'), ('NOTICE', 'Avis'), ('REMINDER', 'Rappel'), ('LEGAL', 'Document légal'), ('OTHER', 'Autre')], default='INVOICE', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description du document')),
                ('is_paid', models.BooleanField(default=False, help_text='Document payé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role__in': ['SUPERADMIN', 'SYNDIC']}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.document'),
        ),
        migrations.CreateModel(
            name='ResidentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_due', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('resident', models.OneToOneField(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statut du résident',
                'verbose_name_plural': 'Statuts des résidents',
            },
        ),
        migrations.DeleteModel(
            name='BankTransaction',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='LegalDocument',
        ),
    ]
