# Generated by Django 5.2.6 on 2025-09-26 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_contribution_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la conversation', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description de la conversation')),
                ('conversation_type', models.CharField(choices=[('GENERAL', 'Général'), ('REPORT', 'Rapport'), ('MAINTENANCE', 'Maintenance'), ('EMERGENCY', 'Urgence')], default='GENERAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salle de Chat',
                'verbose_name_plural': 'Salles de Chat',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Contenu du message')),
                ('message_type', models.CharField(choices=[('TEXT', 'Texte'), ('IMAGE', 'Image'), ('FILE', 'Fichier'), ('SYSTEM', 'Système')], default='TEXT', max_length=10)),
                ('attachment', models.FileField(blank=True, help_text='Fichier joint (image, document, etc.)', null=True, upload_to='chat/%Y/%m/')),
                ('is_read', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='finance.chatmessage')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='finance.chatroom')),
            ],
            options={
                'verbose_name': 'Message de Chat',
                'verbose_name_plural': 'Messages de Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du rapport', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée du problème')),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('SECURITY', 'Sécurité'), ('CLEANING', 'Nettoyage'), ('UTILITIES', 'Services publics'), ('NOISE', 'Bruit'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='PENDING', max_length=15)),
                ('attachment', models.FileField(blank=True, help_text='Fichier joint (photo, document, etc.)', null=True, upload_to='reports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes du syndic')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPERADMIN', 'SYNDIC']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
    ]
