# Generated by Django 5.2.6 on 2025-09-26 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='chat_message',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='report',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='report',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.CreateModel(
            name='ResidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('COMMUNITY', 'Communauté / Voisinage'), ('MAINTENANCE', 'Entretien / Propreté'), ('SECURITY', 'Sécurité / Surveillance'), ('EVENT', 'Évènement / Initiative'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('REVIEWED', 'Révisé'), ('ARCHIVED', 'Archivé')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='resident_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPERADMIN', 'SYNDIC']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport résident',
                'verbose_name_plural': 'Rapports résidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
