# Generated by Django 5.2.6 on 2025-09-26 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_conversation_directmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('MEETING', 'Réunion de copropriété'), ('PAYMENT_DEADLINE', 'Date limite de paiement'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('audience', models.CharField(choices=[('ALL_RESIDENTS', 'Tous les résidents'), ('SPECIFIC', 'Résidents sélectionnés')], default='ALL_RESIDENTS', max_length=20)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=120, help_text="Envoyer une notification X minutes avant l'événement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPERADMIN', 'SYNDIC']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, limit_choices_to={'role': 'RESIDENT'}, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
    ]
