# Generated by Django 5.2.6 on 2025-09-26 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DOCUMENT_CREATED', 'Document créé'), ('DOCUMENT_ARCHIVED', 'Document archivé'), ('PAYMENT_CREATED', 'Paiement enregistré'), ('MESSAGE_SENT', 'Message envoyé'), ('EVENT_CREATED', 'Événement créé')], max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
