# Generated by Django 5.2.6 on 2025-09-27 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_document_archived_at_document_is_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la dépense', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Détails de la dépense')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en DH', max_digits=10)),
                ('categorie', models.CharField(choices=[('ENTRETIEN', 'Entretien'), ('REPARATION', 'Réparation'), ('FACTURE', 'Facture'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('date_depense', models.DateField(default=django.utils.timezone.now, help_text='Date de la dépense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(limit_choices_to={'role__in': ['SUPERADMIN', 'SYNDIC']}, on_delete=django.db.models.deletion.CASCADE, related_name='depenses_ajoutees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-created_at'],
            },
        ),
    ]
