# Generated by Django 5.2.6 on 2025-09-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_depense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='sender',
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='action',
            field=models.CharField(choices=[('DOCUMENT_CREATED', 'Document créé'), ('DOCUMENT_ARCHIVED', 'Document archivé'), ('PAYMENT_CREATED', 'Paiement enregistré'), ('EVENT_CREATED', 'Événement créé')], max_length=40),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
