# Generated by Django 5.2.6 on 2025-09-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_messaging_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverdueNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REMINDER_7', 'Rappel 7 jours'), ('OVERDUE_30', 'Impayé 30 jours'), ('OVERDUE_60', 'Impayé 60 jours'), ('CRITICAL_90', 'Critique 90 jours')], max_length=20)),
                ('sent_to_resident', models.BooleanField(default=False)),
                ('sent_to_syndic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_notifications', to='finance.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('document', 'notification_type')},
            },
        ),
    ]
