# Generated by Django 5.2.6 on 2025-09-27 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_add_overdue_notification_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID de session pour grouper les messages', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question fréquente', max_length=300)),
                ('keywords', models.TextField(help_text='Mots-clés séparés par des virgules (pour détection automatique)')),
                ('answer', models.TextField(help_text='Réponse automatique')),
                ('category', models.CharField(choices=[('PAIEMENT', 'Paiements et Factures'), ('CHARGES', 'Charges de Copropriété'), ('ENTRETIEN', 'Entretien et Réparations'), ('REGLEMENT', 'Règlement Intérieur'), ('CONTACT', 'Contact et Démarches'), ('GENERAL', 'Questions Générales')], default='GENERAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text="Nombre d'utilisations")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['SUPERADMIN', 'SYNDIC']}, on_delete=django.db.models.deletion.CASCADE, related_name='created_faqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Fréquente',
                'verbose_name_plural': 'Questions Fréquentes',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('USER', 'Message Utilisateur'), ('BOT', 'Réponse Bot'), ('FAQ', 'Réponse FAQ Automatique'), ('HUMAN', 'Réponse Humaine (Syndic)')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_helpful', models.BooleanField(blank=True, help_text="L'utilisateur a-t-il trouvé la réponse utile?", null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='finance.chatbotconversation')),
                ('faq_used', models.ForeignKey(blank=True, help_text='FAQ utilisée pour la réponse automatique', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.chatbotfaq')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
