# Generated by Django 5.2.6 on 2025-09-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_add_chatbot_system'),
    ]

    operations = [
    ]
