# Generated by Django 5.2.6 on 2025-09-28 20:56

import django.db.models.deletion
import finance.secure_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_add_is_internal_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50, unique=True, verbose_name='Type de données')),
                ('retention_days', models.PositiveIntegerField(verbose_name='Jours de rétention')),
                ('auto_delete', models.BooleanField(default=False, verbose_name='Suppression automatique')),
                ('anonymize_before_delete', models.BooleanField(default=True, verbose_name='Anonymiser avant suppression')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Politique de rétention',
                'verbose_name_plural': 'Politiques de rétention',
            },
        ),
        migrations.CreateModel(
            name='SecureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_description', finance.secure_models.EncryptedTextField(blank=True, null=True, verbose_name='Description chiffrée')),
                ('encrypted_notes', finance.secure_models.EncryptedTextField(blank=True, null=True, verbose_name='Notes chiffrées')),
                ('encrypted_tags', finance.secure_models.EncryptedTextField(blank=True, null=True, verbose_name='Tags chiffrés')),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash du fichier')),
                ('encryption_status', models.CharField(default='encrypted', max_length=20, verbose_name='Statut de chiffrement')),
                ('access_level', models.CharField(default='confidential', max_length=20, verbose_name="Niveau d'accès")),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Dernier accès')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'accès")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_documents_created', to=settings.AUTH_USER_MODEL)),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_metadata', to='finance.document')),
            ],
            options={
                'verbose_name': 'Document sécurisé',
                'verbose_name_plural': 'Documents sécurisés',
            },
        ),
        migrations.CreateModel(
            name='SecureUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_phone', finance.secure_models.EncryptedTextField(blank=True, null=True, verbose_name='Téléphone chiffré')),
                ('encrypted_address', finance.secure_models.EncryptedTextField(blank=True, null=True, verbose_name='Adresse chiffrée')),
                ('encrypted_apartment', finance.secure_models.EncryptedTextField(blank=True, null=True, verbose_name='Appartement chiffré')),
                ('data_encryption_version', models.CharField(default='1.0', max_length=10, verbose_name='Version de chiffrement')),
                ('last_security_update', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour sécurité')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Authentification à deux facteurs')),
                ('security_questions', finance.secure_models.EncryptedTextField(blank=True, null=True, verbose_name='Questions de sécurité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secure_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil sécurisé',
                'verbose_name_plural': 'Profils sécurisés',
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('DATA_ACCESS', 'Accès aux données'), ('DATA_MODIFY', 'Modification des données'), ('DATA_DELETE', 'Suppression des données'), ('SECURITY_EVENT', 'Événement de sécurité'), ('ADMIN_ACTION', 'Action administrateur')], max_length=20, verbose_name='Action')),
                ('resource', models.CharField(max_length=100, verbose_name='Ressource')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails')),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='LOW', max_length=10, verbose_name='Sévérité')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit de sécurité",
                'verbose_name_plural': "Journaux d'audit de sécurité",
                'ordering': ['-timestamp'],
            },
        ),
    ]
