# Generated by Django 5.2.6 on 2025-09-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_dataretentionpolicy_securedocument_secureuserprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataRetentionPolicy',
        ),
        migrations.RemoveField(
            model_name='secureuserprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='securityauditlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='SecureDocument',
        ),
        migrations.DeleteModel(
            name='SecureUserProfile',
        ),
        migrations.DeleteModel(
            name='SecurityAuditLog',
        ),
    ]
