# Generated by Django 5.2.6 on 2025-09-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_delete_dataretentionpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant en DH (optionnel)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(blank=True, help_text='Date de référence (optionnel)', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='Lien vers un document ou page (optionnel)', max_length=500, null=True),
        ),
    ]
