# Generated by Django 5.2.6 on 2025-09-29 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_notification_amount_notification_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant spécifique pour ce résident', max_digits=10, null=True)),
                ('date', models.DateField(blank=True, help_text='Date spécifique pour ce résident', null=True)),
                ('link', models.URLField(blank=True, help_text='Lien spécifique pour ce résident', max_length=500, null=True)),
                ('custom_message', models.TextField(blank=True, help_text='Message personnalisé pour ce résident', null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_data', to='finance.notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('notification', 'recipient')},
            },
        ),
    ]
