# Generated by Django 5.2.6 on 2025-09-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_notificationrecipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationRecipient',
        ),
    ]
