# Generated by Django 5.2.6 on 2025-10-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_delete_notificationrecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
    ]
