# Generated by Django 5.2.6 on 2025-09-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SYNDIC', 'Gestionnaire Syndic'), ('RESIDENT', 'Résident')], default='RESIDENT', max_length=20),
        ),
    ]
