# Generated by Django 5.2.6 on 2025-09-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_resident',
            field=models.BooleanField(default=False, help_text="Marque si c'est un résident"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrateur'), ('SYNDIC', 'Syndic (Gestionnaire)'), ('RESIDENT', 'Résident')], default='RESIDENT', max_length=20),
        ),
    ]
