# Generated by Django 5.2.6 on 2025-09-26 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_resident_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_residents', to=settings.AUTH_USER_MODEL),
        ),
    ]
