# Generated by Django 5.2.6 on 2025-09-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_created_by'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'RESIDENT'), ('apartment__isnull', False), models.Q(('apartment', ''), _negated=True)), fields=('apartment',), name='unique_apartment_per_resident', violation_error_message='Un résident existe déjà pour cet appartement.'),
        ),
    ]
